import type { Metadata } from 'next'
import './globals.css'
import { Raleway,Inter } from 'next/font/google'
import logo from '../images&svg/kalash_logo.png'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Проекты Академии Калашников',
  description: 'Generated by create next app',
}
const raleway=Raleway( {
subsets :['latin'],
variable:'--font-raleway'
}
)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
      <link rel="icon" href= '../images&svg/kalash_logo.png'/>
      </Head>
      <body className={`${raleway.variable} font-sans`}>{children}</body>
    </html>
  )
}
