import type { Metadata } from 'next'
import './globals.css'
import { Raleway,Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const raleway=Raleway( {
subsets :['latin'],
variable:'--font-raleway'
}
)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} font-sans`}>{children}</body>
    </html>
  )
}
